package com.demo.common.model;

import com.demo.common.model.base.BaseComments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comments extends BaseComments<Comments> {
	public static final Comments dao = new Comments().dao();
}
