package com.demo.common.model;

import com.demo.common.model.base.BaseExchangeTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExchangeTrade extends BaseExchangeTrade<ExchangeTrade> {
	public static final ExchangeTrade dao = new ExchangeTrade().dao();
}
