package com.demo.common.model;

import com.demo.common.model.base.BaseExchangeItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExchangeItem extends BaseExchangeItem<ExchangeItem> {
	public static final ExchangeItem dao = new ExchangeItem().dao();
}
