package com.demo.common.model;

import com.demo.common.model.base.BaseOrderItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderItem extends BaseOrderItem<OrderItem> {
	public static final OrderItem dao = new OrderItem().dao();
	private Book book;

	public Book getBook() {
		return book;
	}

	public void setBook(Book book) {
		this.book = book;
	}
}
