package com.demo.common.model;

import com.demo.common.model.base.BaseSecondTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecondTrade extends BaseSecondTrade<SecondTrade> {
	public static final SecondTrade dao = new SecondTrade().dao();
}
