package com.demo.common.model;

import com.demo.common.model.base.BaseShopcart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shopcart extends BaseShopcart<Shopcart> {
	public static final Shopcart dao = new Shopcart().dao();
}
