package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderItem<M extends BaseOrderItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public M setBookId(java.lang.Integer bookId) {
		set("book_id", bookId);
		return (M)this;
	}

	public java.lang.Integer getBookId() {
		return getInt("book_id");
	}

	public M setPrice(java.lang.Double price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}

	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public M setTotal(java.lang.Double total) {
		set("total", total);
		return (M)this;
	}

	public java.lang.Double getTotal() {
		return getDouble("total");
	}

	public M setPriceType(java.lang.String priceType) {
		set("price_type", priceType);
		return (M)this;
	}

	public java.lang.String getPriceType() {
		return getStr("price_type");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
