package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExchangeItem<M extends BaseExchangeItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setCommented(java.lang.Integer commented) {
		set("commented", commented);
		return (M)this;
	}

	public java.lang.Integer getCommented() {
		return getInt("commented");
	}

	public M setOrderItemId(java.lang.String orderItemId) {
		set("order_item_id", orderItemId);
		return (M)this;
	}

	public java.lang.String getOrderItemId() {
		return getStr("order_item_id");
	}

	public M setBookId(java.lang.Integer bookId) {
		set("book_id", bookId);
		return (M)this;
	}

	public java.lang.Integer getBookId() {
		return getInt("book_id");
	}

	public M setPrice(java.lang.Double price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}

	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public M setTotal(java.lang.Double total) {
		set("total", total);
		return (M)this;
	}

	public java.lang.Double getTotal() {
		return getDouble("total");
	}

	public M setPriceType(java.lang.String priceType) {
		set("price_type", priceType);
		return (M)this;
	}

	public java.lang.String getPriceType() {
		return getStr("price_type");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
