package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExchangeTrade<M extends BaseExchangeTrade<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUserExchangeItemId(java.lang.Integer userExchangeItemId) {
		set("user_exchange_item_id", userExchangeItemId);
		return (M)this;
	}

	public java.lang.Integer getUserExchangeItemId() {
		return getInt("user_exchange_item_id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setBuyerId(java.lang.Integer buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}

	public java.lang.Integer getBuyerId() {
		return getInt("buyer_id");
	}

	public M setBuyerExchangeItemId(java.lang.Integer buyerExchangeItemId) {
		set("buyer_exchange_item_id", buyerExchangeItemId);
		return (M)this;
	}

	public java.lang.Integer getBuyerExchangeItemId() {
		return getInt("buyer_exchange_item_id");
	}

}
